=== EresK/DIContainer/src/main/resources/schema.json
{
  "$id": "di-container/schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Bean Definition",
  "description": "A schema for BeanDefinition class",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "description": "name of a bean",
        "type": "string"
      },
      "class": {
        "description": "java.class.of.a.Bean",
        "type": "string"
      },
      "scope": {
        "description": "singleton(default), prototype, thread",
        "default": "singleton",
        "enum": [
          "singleton",
          "prototype",
          "thread"
        ],
        "type": "string"
      },
      "primary": {
        "description": "defines a primary implementation for specific interface",
        "default": false,
        "type": "boolean"
      },
      "lazy-init": {
        "description": "defines lazy initialization for a singleton bean",
        "default": false,
        "type": "boolean"
      },
      "constructor-args": {
        "description": "defines constructor arguments as java primitives/string, or reference to another bean",
        "type": "array",
        "items": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "type": {
                  "description": "java.type.of.an.Primitive or String",
                  "type": "string"
                },
                "value": {
                  "description": "value of the type",
                  "type": [
                    "string",
                    "integer",
                    "number",
                    "boolean"
                  ]
                }
              },
              "required": [
                "type",
                "value"
              ]
            },
            {
              "type": "object",
              "properties": {
                "type": {
                  "description": "java.path.to.Bean",
                  "type": "string"
                },
                "ref": {
                  "description": "name of another bean",
                  "type": "string"
                }
              },
              "required": [
                "type",
                "ref"
              ]
            }
          ]
        }
      },
      "property-args": {
        "description": "defines property arguments as java primitives/string, or reference to another bean",
        "type": "array",
        "items": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "description": "name of a field",
                  "type": "string"
                },
                "type": {
                  "description": "java.type.to.Primitive",
                  "type": "string"
                },
                "value": {
                  "description": "value of the type",
                  "type": [
                    "string",
                    "integer",
                    "number",
                    "boolean"
                  ]
                }
              },
              "required": [
                "name",
                "type",
                "value"
              ]
            },
            {
              "type": "object",
              "properties": {
                "name": {
                  "description": "name of another bean",
                  "type": "string"
                },
                "ref": {
                  "description": "java.type.to.Bean",
                  "type": "string"
                }
              },
              "required": [
                "name",
                "ref"
              ]
            }
          ]
        }
      }
    },
    "required": [
      "name",
      "class"
    ]
  }
}

=== EresK/DIContainer/src/test/resources/config/basic-config.json
[
  {
    "name": "server",
    "class": "di.container.example.server.NodeJSWebServer",
    "scope": "prototype",
    "constructor-args": [
      {
        "type": "di.container.example.database.PostgresDataBase",
        "ref": "dataBase"
      },
      {
        "type": "java.lang.String",
        "value": "active"
      }
    ]
  },
  {
    "name": "dataBase",
    "class": "di.container.example.database.PostgresDataBase",
    "scope": "singleton",
    "constructor-args": [
      {
        "type": "java.lang.Integer",
        "value": 15
      }
    ]
  }
]
